stages:
  - test
  - secret-detection
  - triggers

variables:
  SECRET_DETECTION_ENABLED: 'true'

# Security Scans (active globally)
sast:
  stage: test

secret_detection:
  stage: secret-detection

include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

# Parent-child pipeline triggers
trigger-frontend:
  stage: triggers
  trigger:
    include: frontend/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - frontend/**/*
      when: on_success

trigger-terraform:
  stage: triggers
  trigger:
    include: infra/terraform/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - infra/terraform/**/*
      when: on_success
