stages:
  - triggers

# Parent-child pipeline triggers
trigger-frontend:
  stage: triggers
  trigger:
    include: frontend/.gitlab-ci.yml
    strategy: depend
  rules:
    - changes:
        - frontend/**/*
      when: on_success

# trigger-terraform:
#   stage: triggers
#   trigger:
#     include: infra/terraform/.gitlab-ci.yml
#     strategy: depend
#   rules:
#     - changes:
#         - infra/terraform/**/*
#       when: on_success

